# Generated by Django 3.1.7 on 2021-04-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0002_task_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-completed']},
        ),
    ]
