# Generated by Django 3.1.7 on 2021-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0005_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
