# Generated by Django 3.1.7 on 2021-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0008_auto_20210502_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
